import type { LucideIcon } from "lucide-react";
import { ArrowDown, ArrowRight, BarChart3, BellRing, Bot, CheckCircle2, CircleX, ClipboardCheck, HeartHandshake, MessagesSquare, Network, Route, ShieldCheck, Smartphone, Users, Waypoints } from "lucide-react";
import Link from "next/link";
import { PageStructuredData } from "@/components/seo-json-ld";
import { createMetadata } from "@/lib/seo";

const path = "/programmes/screenconnect" as const;
const description = "ScreenConnect™ is BloomShield CIC’s patient-navigation and care-coordination programme, helping people remain connected from cancer screening through referral, diagnosis, treatment and follow-up.";
export const metadata = createMetadata({ title: "ScreenConnect™ | Digital Patient Navigation and Connected Care | BloomShield CIC", description, path, absoluteTitle: true });
const contactHref = "/contact?programme=screenconnect";

const barriers = ["Missed appointments", "Unclear referrals", "Fragmented communication", "Fear or uncertainty", "Transport barriers", "Financial pressures", "Language barriers", "Digital exclusion", "Limited navigation support", "Weak follow-up systems"];
const pillars: { icon: LucideIcon; title: string; summary: string; items: string[] }[] = [
  { icon: Waypoints, title: "Digital Patient Navigation", summary: "Clear, practical support through each next step.", items: ["Appointment reminders", "Referral guidance", "Preparation instructions", "Transport information", "Multilingual communication", "Navigator support", "Clear next-step information"] },
  { icon: Network, title: "Connected Care Coordination", summary: "Joining up the people and services around a pathway.", items: ["Primary care", "Screening providers", "Diagnostic clinics", "Hospitals", "Multidisciplinary teams", "Community organisations", "Patient navigators", "Patients and families"] },
  { icon: MessagesSquare, title: "Digital Follow-up", summary: "Inclusive communication chosen around people, not technology alone.", items: ["SMS", "Email", "Telephone", "Secure messaging", "Patient portals", "Community health workers", "Navigator outreach"] },
  { icon: BarChart3, title: "Data Intelligence", summary: "Implementation indicators that support learning and improvement.", items: ["Referral completion", "Attendance", "Waiting times", "Missed appointments", "Treatment initiation", "Follow-up completion", "Navigation outcomes", "Pathway inequalities"] },
  { icon: HeartHandshake, title: "Equity and Inclusion", summary: "Navigation designed around people who experience greater barriers.", items: ["Older adults", "Minority ethnic communities", "Migrants and refugees", "People with disabilities", "People with limited digital access", "Rural or underserved communities", "People facing financial or transport barriers"] },
];
const journey = ["Community awareness through ScreenSmart Communities™", "Screening appointment arranged", "Screening completed", "Result or referral communicated", "ScreenConnect™ navigation begins", "Next steps explained", "Diagnostic appointment coordinated", "Reminder and practical support provided", "Diagnosis or treatment pathway completed", "Follow-up scheduled", "Ongoing monitoring or survivorship support"];
const isItems = ["A patient-navigation framework", "A care-coordination approach", "A digital communication pathway", "An implementation-support programme", "A bridge between community and clinical services", "A system for reducing avoidable loss to follow-up"];
const isNotItems = ["An electronic health record", "A replacement for NHS or clinical systems", "A diagnostic tool", "An emergency service", "A standalone reminder application", "A substitute for clinical judgement", "A promise of automatic interoperability"];
const future = [
  ["ScreenConnect Navigator™", "A trained patient-navigation and community-support workforce.", Users],
  ["ScreenConnect Digital™", "Secure digital communication, pathway information and patient-support tools.", Smartphone],
  ["ScreenConnect Analytics™", "Implementation dashboards supporting programme monitoring, evaluation and service improvement.", BarChart3],
  ["ScreenConnect Community™", "Community organisations and trusted local partners supporting people throughout the pathway.", HeartHandshake],
] as const;
const outcomes = ["Improved referral completion", "Reduced avoidable loss to follow-up", "Improved appointment attendance", "Clearer communication", "Faster movement through appropriate pathways", "Improved patient experience", "Stronger continuity of care", "Improved pathway equity", "Better implementation data", "Improved coordination between community and clinical services"];
const implementation = [
  ["Understand", "Map the pathway, communities, services, barriers and points where people are lost."],
  ["Connect", "Bring together patients, navigators, community organisations and healthcare providers."],
  ["Navigate", "Deliver coordinated information, reminders, practical support and follow-up."],
  ["Evaluate", "Measure attendance, referral completion, experience, equity and implementation outcomes."],
  ["Scale", "Strengthen and extend approaches that prove feasible, acceptable and effective."],
] as const;
const partners = ["NHS organisations", "Integrated care boards", "Primary care networks", "Cancer alliances", "Screening providers", "Hospitals", "Local authorities", "Voluntary and community organisations", "Universities", "Digital-health organisations", "Funders", "Patient groups"];

function SectionTitle({ eyebrow, title, intro }: { eyebrow: string; title: string; intro?: string }) {
  return <div className="max-w-3xl"><p className="screenconnect-eyebrow">{eyebrow}</p><h2 className="screenconnect-heading">{title}</h2>{intro && <p className="mt-5 text-lg leading-8 text-slate-600">{intro}</p>}</div>;
}
function List({ items, negative = false }: { items: readonly string[]; negative?: boolean }) {
  const Icon = negative ? CircleX : CheckCircle2;
  return <ul className="mt-6 space-y-3">{items.map(item => <li key={item} className="flex gap-3 leading-7 text-slate-700"><Icon aria-hidden="true" className={`mt-1 shrink-0 ${negative ? "text-slate-500" : "text-[#3858c7]"}`} size={19}/><span>{item}</span></li>)}</ul>;
}

export default function ScreenConnect() {
  return <>
    <PageStructuredData name="ScreenConnect™" description={description} path={path} breadcrumb="ScreenConnect™" kind="screenconnect" />
    <section className="screenconnect-hero">
      <div aria-hidden="true" className="screenconnect-network"><i/><i/><i/><i/><i/></div>
      <div className="container-page relative grid min-h-[720px] min-w-0 items-center gap-12 py-20 lg:grid-cols-[1.12fr_.88fr]">
        <div className="min-w-0">
          <nav aria-label="Breadcrumb" className="mb-8 text-sm text-blue-100/80"><ol className="flex flex-wrap items-center gap-2"><li><Link href="/">Home</Link></li><li aria-hidden="true">/</li><li><Link href="/programmes">Programmes</Link></li><li aria-hidden="true">/</li><li aria-current="page" className="text-white">ScreenConnect™</li></ol></nav>
          <p className="text-xs font-bold uppercase tracking-[.2em] text-blue-200">BloomShield Programme Portfolio · Volume 3</p>
          <h1 className="mt-6 font-display text-4xl font-semibold leading-[1.02] tracking-[-.04em] sm:text-6xl lg:text-7xl">ScreenConnect™</h1>
          <p className="mt-6 max-w-3xl font-display text-2xl font-semibold leading-snug text-blue-100 sm:text-3xl">Connecting People. Connecting Care. Connecting Outcomes.</p>
          <p className="mt-7 max-w-2xl text-lg leading-8 text-white/80">A digital patient-navigation and care-coordination programme designed to help people remain connected from screening through referral, diagnosis, treatment, follow-up and survivorship.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href={contactHref} className="screenconnect-button">Partner With ScreenConnect™ <ArrowRight size={17}/></Link><Link href="#overview" className="screenconnect-button-outline">Explore the Programme <ArrowDown size={17}/></Link></div>
        </div>
        <aside className="rounded-[2.25rem] border border-white/15 bg-white/[.08] p-7 shadow-2xl backdrop-blur-sm sm:p-9"><Route className="h-12 w-12 text-[#ff9b7f]" strokeWidth={1.5}/><p className="mt-7 font-display text-3xl font-semibold leading-tight">No one should be lost between screening and treatment.</p><ol className="mt-8 space-y-3">{["Screening", "Referral", "Diagnosis", "Treatment", "Follow-up"].map((item,index) => <li key={item} className="flex items-center gap-4 rounded-2xl bg-white/[.08] p-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-200 text-xs font-bold text-[#102767]">0{index + 1}</span><span className="font-semibold">{item}</span></li>)}</ol></aside>
      </div>
    </section>

    <section id="overview" className="section-space scroll-mt-24 bg-[#f5f7ff]"><div className="container-page grid gap-12 lg:grid-cols-[.78fr_1.22fr]"><SectionTitle eyebrow="Programme overview" title="Screening alone does not guarantee better outcomes."/><div className="space-y-5 text-lg leading-8 text-slate-700"><p>People can still be lost between screening, referral, diagnosis, treatment and follow-up. ScreenConnect™ creates a supported pathway through which people receive clear information, timely reminders, navigation assistance and coordinated follow-up.</p><p>It is the coordination and navigation layer that helps existing services work together and enables people to complete their care pathway.</p><div className="grid gap-3"><ProgrammeStatement href="/programmes/screensmart-communities" accent="green" icon={Users} name="ScreenSmart Communities™" statement="inspires action."/><ProgrammeStatement href="/programmes/screenaccess" accent="coral" icon={Route} name="ScreenAccess™" statement="enables access."/><ProgrammeStatement href="/programmes/screenconnect" accent="blue" icon={Waypoints} name="ScreenConnect™" statement="sustains the journey."/></div></div></div></section>
    <section className="section-space"><div className="container-page"><SectionTitle eyebrow="Where pathways break" title="Practical, emotional and system barriers can interrupt care."/><ul className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{barriers.map(item => <li key={item} className="flex items-center gap-3 rounded-2xl border border-blue-900/10 bg-white p-5 font-semibold text-slate-800 shadow-sm"><BellRing className="shrink-0 text-[#3858c7]" size={19}/>{item}</li>)}</ul></div></section>
    <section className="section-space bg-[#122864]"><div className="container-page grid gap-6 lg:grid-cols-2"><Purpose label="Vision" title="The right care, at the right time.">To create an intelligent and inclusive navigation ecosystem that keeps every person connected to the right care, at the right time, throughout the cancer journey.</Purpose><Purpose label="Mission" title="One connected pathway.">To reduce loss to follow-up by combining patient navigation, digital communication, care coordination, implementation data and community support within one connected pathway.</Purpose></div></section>
    <section className="section-space bg-[#f8f9ff]"><div className="container-page"><SectionTitle eyebrow="Five programme pillars" title="Human navigation supported by connected systems."/><div className="mt-12 grid gap-6 lg:grid-cols-2">{pillars.map(({icon:Icon,title,summary,items}, index) => <article key={title} className={`screenconnect-card ${index === 4 ? "lg:col-span-2" : ""}`}><div className="flex gap-5"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-[#3858c7] text-white"><Icon size={23}/></span><div><p className="text-xs font-bold uppercase tracking-widest text-[#5267c9]">Pillar {index + 1}</p><h3 className="mt-2 font-display text-2xl font-semibold text-[#1d337d]">{title}</h3><p className="mt-2 leading-7 text-slate-600">{summary}</p></div></div><div className="mt-6 flex flex-wrap gap-2">{items.map(item => <span key={item} className="rounded-full bg-[#edf0ff] px-4 py-2 text-sm font-semibold text-[#243c89]">{item}</span>)}</div></article>)}</div></div></section>
    <section className="section-space overflow-hidden bg-[#10245c] text-white"><div className="container-page"><p className="screenconnect-dark-eyebrow">Illustrative connected patient journey</p><h2 className="font-display text-4xl font-semibold sm:text-5xl">Awareness to ongoing support—without losing the thread.</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-white/75">This sequence illustrates how navigation may support an existing care pathway. Clinical responsibility remains with qualified healthcare professionals and recognised services.</p><ol className="screenconnect-journey mt-14">{journey.map((item,index) => <li key={item}><span>{index + 1}</span><p>{item}</p></li>)}</ol></div></section>
    <section className="section-space"><div className="container-page"><SectionTitle eyebrow="Clear scope" title="What ScreenConnect™ is—and what it is not."/><div className="mt-12 grid gap-6 lg:grid-cols-2"><article className="screenconnect-card"><h3 className="font-display text-3xl font-semibold text-[#1d337d]">ScreenConnect™ is</h3><List items={isItems}/></article><article className="screenconnect-card"><h3 className="font-display text-3xl font-semibold text-slate-700">ScreenConnect™ is not</h3><List items={isNotItems} negative/></article></div></div></section>
    <section className="section-space bg-[#f5f7ff]"><div className="container-page"><SectionTitle eyebrow="Future programme components" title="A responsible development pipeline." intro="These are future development concepts, not currently deployed products. Their form and use will be shaped with communities, clinical partners and delivery organisations."/><div className="mt-12 grid gap-5 md:grid-cols-2">{future.map(([title,text,Icon]) => <article key={title} className="screenconnect-card"><Icon className="text-[#3858c7]" size={30}/><h3 className="mt-6 font-display text-2xl font-semibold text-[#1d337d]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}<article className="screenconnect-card border-[#ff8e70]/35"><Bot className="text-[#c8583c]" size={30}/><p className="mt-5 text-xs font-bold uppercase tracking-widest text-[#b34b34]">Exploratory concept</p><h3 className="mt-2 font-display text-2xl font-semibold text-[#1d337d]">ScreenConnect AI™</h3><p className="mt-3 leading-7 text-slate-600">Potential future responsible use of artificial intelligence for pathway support, prioritisation and implementation insight. Any development would be subject to clinical governance, ethical review, evidence, data protection and regulatory requirements. No operational AI system is implied.</p></article></div></div></section>
    <section className="section-space"><div className="container-page"><SectionTitle eyebrow="Intended outcomes" title="Designed to support better continuity and coordination." intro="ScreenConnect™ aims to support these outcomes. Results will depend on context, delivery partners and the approaches agreed; no clinical or financial outcome is guaranteed."/><ul className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{outcomes.map(item => <li key={item} className="flex gap-3 rounded-2xl border border-blue-900/10 p-5 font-semibold"><CheckCircle2 className="mt-0.5 shrink-0 text-[#3858c7]" size={20}/>{item}</li>)}</ul></div></section>
    <section className="section-space bg-[#f8f9ff]"><div className="container-page"><SectionTitle eyebrow="BloomShield programme portfolio" title="Three distinct questions. One connected pathway."/><div className="mt-12 grid gap-6 lg:grid-cols-3"><Portfolio href="/programmes/screensmart-communities" accent="green" name="ScreenSmart Communities™" role="Builds awareness, confidence and demand for screening." question="Will people take action?"/><Portfolio href="/programmes/screenaccess" accent="coral" name="ScreenAccess™" role="Removes practical, geographic, financial and structural barriers to screening." question="Can people reach the service?"/><Portfolio href={path} accent="blue" name="ScreenConnect™" role="Supports navigation, referral completion, treatment and follow-up." question="Will people complete the pathway?"/></div><p className="mx-auto mt-12 max-w-3xl text-center font-display text-2xl font-semibold leading-10 text-[#1d337d]">ScreenSmart Communities™ inspires action.<br/>ScreenAccess™ enables access.<br/>ScreenConnect™ sustains the journey.</p></div></section>
    <section className="section-space bg-[#10245c] text-white"><div className="container-page"><p className="screenconnect-dark-eyebrow">CCPE implementation pathway</p><h2 className="font-display text-4xl font-semibold sm:text-5xl">Understand → Connect → Navigate → Evaluate → Scale</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-white/75">Aligned with BloomShield’s <Link href="/about#ccpe" className="font-bold text-blue-200 underline underline-offset-4">Cancer Care Partnership Ecosystem</Link>.</p><ol className="screenconnect-pathway mt-14">{implementation.map(([title,text],index) => <li key={title}><span>{index + 1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></div></section>
    <section className="section-space"><div className="container-page grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><SectionTitle eyebrow="Partnership" title="Build a connected cancer-care pathway with BloomShield."/><Link href={contactHref} className="screenconnect-link mt-8">Discuss a ScreenConnect™ Partnership <ArrowRight size={17}/></Link></div><ul className="grid gap-3 sm:grid-cols-2">{partners.map(partner => <li key={partner} className="flex items-center gap-3 rounded-xl border border-blue-900/10 p-4 font-semibold"><Network className="shrink-0 text-[#3858c7]" size={19}/>{partner}</li>)}</ul></div></section>
    <section className="section-space bg-[#f5f7ff]"><div className="container-page grid gap-12 lg:grid-cols-2"><div><SectionTitle eyebrow="Programme development" title="Built carefully, tested collaboratively."/><p className="mt-6 text-lg leading-8 text-slate-700">ScreenConnect™ is intended to complement established services. Delivery models, communication channels, evaluation measures and governance will be agreed with partners and communities.</p><div className="mt-7 flex gap-4 rounded-2xl border-l-4 border-[#3858c7] bg-white p-6"><ShieldCheck className="mt-1 shrink-0 text-[#3858c7]"/><p className="leading-7 text-slate-700"><strong>Clinical responsibility:</strong> Diagnosis, treatment, urgent care and clinical judgement remain the responsibility of appropriately qualified professionals and recognised health services.</p></div></div><aside className="rounded-[2rem] border border-blue-900/15 bg-white p-8 sm:p-10" role="status" aria-label="ScreenConnect programme overview availability"><ClipboardCheck className="h-10 w-10 text-[#3858c7]"/><p className="mt-7 screenconnect-eyebrow">Programme literature</p><h2 className="font-display text-3xl font-semibold text-[#1d337d]">ScreenConnect™ Programme Overview</h2><div className="mt-7 rounded-2xl border border-dashed border-blue-900/25 bg-[#f8f9ff] p-6"><p className="font-bold text-[#1d337d]">Programme Overview Coming Soon</p><p className="mt-3 leading-7 text-slate-600">A downloadable overview will be published after programme development. There is no download available at present.</p></div></aside></div></section>
    <section className="screenconnect-closing"><div className="container-page relative py-20 text-center sm:py-24"><p className="screenconnect-dark-eyebrow">Connecting the pathway</p><h2 className="mx-auto max-w-4xl font-display text-4xl font-semibold sm:text-5xl">No one should be lost between screening and treatment.</h2><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-white/80">Work with BloomShield to explore a human, inclusive and evidence-informed approach to patient navigation and care coordination.</p><Link href={contactHref} className="screenconnect-closing-button mt-9">Discuss a ScreenConnect™ Partnership <ArrowRight aria-hidden="true" size={17}/></Link></div></section>
  </>;
}

function Purpose({label,title,children}:{label:string;title:string;children:string}) {
  return <article className="screenconnect-purpose-card rounded-3xl border p-8 sm:p-10"><p className="screenconnect-eyebrow">{label}</p><h2 className="font-display text-3xl font-semibold text-[#14265b]">{title}</h2><p className="mt-5 text-lg leading-8 text-slate-700">{children}</p></article>;
}
function ProgrammeStatement({href,accent,icon:Icon,name,statement}:{href:string;accent:"green"|"coral"|"blue";icon:LucideIcon;name:string;statement:string}) {
  return <Link href={href} className={`screenconnect-programme-link screenconnect-programme-link-${accent}`}><span className="screenconnect-programme-link-icon"><Icon aria-hidden="true" size={22}/></span><span className="min-w-0"><strong className="block font-display text-xl leading-7">{name}</strong><span className="block text-base leading-7 text-slate-700">{statement}</span></span><ArrowRight aria-hidden="true" className="ml-auto shrink-0" size={21}/></Link>;
}
function Portfolio({href,accent,name,role,question}:{href:string;accent:"green"|"coral"|"blue";name:string;role:string;question:string}) {
  const colours = {green:"border-emerald-600 bg-emerald-50 text-emerald-950",coral:"border-[#c8583c] bg-[#fff3ee] text-[#71301f]",blue:"border-[#3858c7] bg-[#edf0ff] text-[#1d337d]"};
  return <article className={`rounded-3xl border-t-4 p-7 ${colours[accent]}`}><Link href={href} className="font-display text-2xl font-semibold underline decoration-2 underline-offset-4">{name}</Link><p className="mt-5 leading-7">{role}</p><p className="mt-6 text-sm font-bold uppercase tracking-wider">Core question</p><p className="mt-2 font-display text-xl font-semibold">{question}</p></article>;
}
