import type { LucideIcon } from "lucide-react";
import { ArrowDown, ArrowRight, BarChart3, BellRing, CheckCircle2, CircleX, HeartHandshake, MessagesSquare, Network, Route, ShieldCheck, Users, Waypoints } from "lucide-react";
import Link from "next/link";
import { PathwayInfographic } from "@/components/pathway-infographic";
import { ProgrammeOverviewDownload } from "@/components/programme-overview-download";
import { PageStructuredData } from "@/components/seo-json-ld";
import { createMetadata } from "@/lib/seo";

const path = "/programmes/screenconnect" as const;
const overviewPdf = "/downloads/programmes/bloomshield-screenconnect-programme-overview-v1.pdf";
const description = "ScreenConnect Digital™ is BloomShield’s discovery-stage community-to-pathway navigation and outcome-assurance innovation, designed to strengthen progression from community engagement to screening, referral and completed next steps.";
export const metadata = createMetadata({
  title: "ScreenConnect™ Digital | Navigation & Pathway Assurance | BloomShield",
  description,
  path,
  absoluteTitle: true,
  socialImage: {
    url: "/images/screenconnect-digital-pathway-infographic.png",
    width: 1672,
    height: 941,
    alt: "ScreenConnect Digital pathway from community outreach and engagement to navigation closure, with community-led and provider-confirmed stages.",
    type: "image/png",
  },
});
const contactHref = "/contact?programme=screenconnect";

const barriers = ["Unclear information", "Low health literacy", "Fear and anxiety", "Language and cultural barriers", "Transport barriers", "Financial pressures", "Digital exclusion", "Fragmented referrals", "Missed appointments", "Poor communication", "Weak follow-up", "Limited navigation support", "System barriers"];
const continuum = ["Prevention", "Screening", "Referral", "Diagnosis", "Treatment", "Follow-up", "Survivorship"];
const navigationBenefits: { icon: LucideIcon; title: string; summary: string }[] = [
  { icon: Route, title: "Earlier diagnosis", summary: "Helping people understand and complete appropriate next steps may reduce avoidable delays to diagnosis." },
  { icon: Network, title: "Better continuity", summary: "Care coordination can strengthen connections between community, screening, diagnostic and treatment services." },
  { icon: Waypoints, title: "Reduced loss to follow-up", summary: "Structured patient tracking and follow-up can help identify when someone risks becoming disconnected from care." },
  { icon: HeartHandshake, title: "Improved patient experience", summary: "Clear information and practical, culturally responsive support can make complex pathways easier to navigate." },
  { icon: Users, title: "More equitable care", summary: "Barrier-led navigation can focus support where practical, communication, digital and system barriers are greatest." },
];
const pillars: { icon: LucideIcon; title: string; summary: string; items: string[] }[] = [
  { icon: Waypoints, title: "Digital Patient Navigation", summary: "Clear, practical support through each next step.", items: ["Appointment reminders", "Referral guidance", "Preparation instructions", "Transport information", "Multilingual communication", "Navigator support", "Clear next-step information"] },
  { icon: Network, title: "Connected Care Coordination", summary: "Joining up the people and services around a pathway.", items: ["Primary care", "Screening providers", "Diagnostic clinics", "Hospitals", "Multidisciplinary teams", "Community organisations", "Patient navigators", "Patients and families"] },
  { icon: MessagesSquare, title: "Digital Follow-up", summary: "Inclusive communication chosen around people, not technology alone.", items: ["SMS", "Email", "Telephone", "Secure messaging", "Patient portals", "Community health workers", "Navigator outreach"] },
  { icon: BarChart3, title: "Navigation Intelligence & Improvement", summary: "Proportionate implementation indicators that support learning and service improvement—not a live software platform.", items: ["Pathway completion", "Barrier profiles", "Navigation interventions", "Drop-out points", "Referral completion", "Patient tracking", "Equity indicators", "Implementation learning"] },
  { icon: HeartHandshake, title: "Equity and Inclusion", summary: "Navigation designed around people who experience greater barriers.", items: ["Older adults", "Minority ethnic communities", "Migrants and refugees", "People with disabilities", "People with limited digital access", "Rural or underserved communities", "People facing financial or transport barriers"] },
];
const journey = ["Barrier identification", "Pre-screening support", "Screening", "Results", "Referral navigation", "Confirmatory diagnosis", "Patient tracking", "Follow-up", "Treatment connection", "Survivorship"];
const isItems = ["An evidence-informed patient-navigation framework", "A care-coordination approach", "A digital communication pathway", "Structured patient tracking", "Implementation support", "Barrier identification", "A bridge between community and clinical services", "A framework for reducing avoidable pathway loss"];
const isNotItems = ["An electronic health record", "A replacement for NHS or clinical systems", "A diagnostic tool", "An emergency service", "A standalone reminder application", "A substitute for clinical judgement", "A promise of automatic interoperability"];
const future = [
  ["ScreenConnect Navigator™", "A trained patient-navigation and community-support workforce.", Users],
  ["ScreenConnect Analytics™", "Implementation dashboards supporting programme monitoring, evaluation and service improvement.", BarChart3],
  ["ScreenConnect Community™", "Community organisations and trusted local partners supporting people throughout the pathway.", HeartHandshake],
] as const;
const digitalModes = [
  ["Community / independent navigation", ["Engagement and intake", "Barrier identification", "Navigation support", "Referral / signposting", "Follow-up", "Programme assurance"]],
  ["NHS-linked pathway assurance", ["Provider-confirmed milestones", "Verified attendance / completion", "Approved pathway-status exchange", "Stronger outcome assurance"]],
] as const;
const outcomes = ["Improved pathway completion", "Reduced avoidable loss to follow-up", "Improved appointment attendance", "Clearer communication", "Improved patient experience", "Improved pathway equity", "Improved care coordination", "Useful navigation data", "Implementation learning"];
const implementation = [
  ["Understand", "Map the pathway, communities, services, barriers and points where people are lost."],
  ["Connect", "Bring together patients, navigators, community organisations and healthcare providers."],
  ["Navigate", "Deliver coordinated information, reminders, practical support and follow-up."],
  ["Evaluate", "Measure attendance, referral completion, experience, equity and implementation outcomes."],
  ["Scale", "Strengthen and extend approaches that prove feasible, acceptable and effective."],
] as const;
const partners = ["NHS organisations", "Integrated care boards (ICBs)", "Cancer alliances", "Local authorities", "Hospitals", "Primary care networks (PCNs)", "Universities", "Charities", "International partners", "Global health funders"];

function SectionTitle({ eyebrow, title, intro }: { eyebrow: string; title: string; intro?: string }) {
  return <div className="max-w-3xl"><p className="screenconnect-eyebrow">{eyebrow}</p><h2 className="screenconnect-heading">{title}</h2>{intro && <p className="mt-5 text-lg leading-8 text-slate-600">{intro}</p>}</div>;
}
function List({ items, negative = false }: { items: readonly string[]; negative?: boolean }) {
  const Icon = negative ? CircleX : CheckCircle2;
  return <ul className="mt-6 space-y-3">{items.map(item => <li key={item} className="flex gap-3 leading-7 text-slate-700"><Icon aria-hidden="true" className={`mt-1 shrink-0 ${negative ? "text-slate-500" : "text-[#3858c7]"}`} size={19}/><span>{item}</span></li>)}</ul>;
}

export default function ScreenConnect() {
  return <>
    <PageStructuredData name="ScreenConnect™" description={description} path={path} breadcrumb="ScreenConnect™" kind="screenconnect" />
    <section className="screenconnect-hero">
      <div aria-hidden="true" className="screenconnect-network"><i/><i/><i/><i/><i/></div>
      <div className="container-page relative grid min-h-[720px] min-w-0 items-center gap-12 py-20 lg:grid-cols-[1.12fr_.88fr]">
        <div className="min-w-0">
          <nav aria-label="Breadcrumb" className="mb-8 text-sm text-blue-100/80"><ol className="flex flex-wrap items-center gap-2"><li><Link href="/">Home</Link></li><li aria-hidden="true">/</li><li><Link href="/programmes">Programmes</Link></li><li aria-hidden="true">/</li><li aria-current="page" className="text-white">ScreenConnect™</li></ol></nav>
          <p className="text-xs font-bold uppercase tracking-[.2em] text-blue-200">BloomShield Programme Portfolio · Volume 3</p>
          <h1 className="mt-6 font-display text-4xl font-semibold leading-[1.02] tracking-[-.04em] sm:text-6xl lg:text-7xl">ScreenConnect™</h1>
          <p className="mt-6 max-w-3xl font-display text-2xl font-semibold leading-snug text-blue-100 sm:text-3xl">Connecting People. Connecting Care. Connecting Outcomes.</p>
          <p className="mt-7 max-w-2xl text-lg leading-8 text-white/80">ScreenConnect™ is BloomShield&apos;s patient-navigation and care-coordination programme, designed to identify and overcome barriers that prevent people progressing through the cancer care continuum—from screening and referral through diagnosis, treatment, follow-up and survivorship.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href={contactHref} className="screenconnect-primary-button">Partner With ScreenConnect™ <ArrowRight aria-hidden="true" size={17}/></Link><Link href="#overview" className="screenconnect-button-outline">Explore the Programme <ArrowDown size={17}/></Link></div>
        </div>
        <aside className="rounded-[2.25rem] border border-white/15 bg-white/[.08] p-7 shadow-2xl backdrop-blur-sm sm:p-9"><Route className="h-12 w-12 text-[#ff9b7f]" strokeWidth={1.5}/><p className="mt-7 font-display text-3xl font-semibold leading-tight">No one should be lost between screening and treatment.</p><ol className="mt-8 space-y-3">{["Screening", "Referral", "Diagnosis", "Treatment", "Follow-up"].map((item,index) => <li key={item} className="flex items-center gap-4 rounded-2xl bg-white/[.08] p-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-200 text-xs font-bold text-[#102767]">0{index + 1}</span><span className="font-semibold">{item}</span></li>)}</ol></aside>
      </div>
    </section>

    <section id="overview" className="section-space scroll-mt-24 bg-[#f5f7ff]"><div className="container-page grid gap-12 lg:grid-cols-[.78fr_1.22fr]"><SectionTitle eyebrow="Programme overview" title="Screening alone does not guarantee better outcomes."/><div className="space-y-5 text-lg leading-8 text-slate-700"><p>Cancer pathways can be fragmented. Practical, emotional, cultural, communication, digital and system barriers can delay diagnosis or treatment and lead to avoidable loss to follow-up—even when screening and clinical services are available.</p><p>ScreenConnect™ is BloomShield&apos;s navigation solution: an evidence-informed patient-navigation and care-coordination framework that identifies barriers, clarifies next steps, supports referrals, tracks progress and coordinates follow-up across the cancer care continuum.</p><p>It adds a human navigation and implementation layer around existing services, helping people remain connected while clinical responsibility stays with qualified healthcare professionals.</p><div className="grid gap-3"><ProgrammeStatement href="/programmes/screensmart-communities" accent="green" icon={Users} name="ScreenSmart Communities™" statement="inspires action."/><ProgrammeStatement href="/programmes/screenaccess" accent="coral" icon={Route} name="ScreenAccess™" statement="enables access."/><ProgrammeStatement href="/programmes/screenconnect" accent="blue" icon={Waypoints} name="ScreenConnect™" statement="sustains the journey."/></div></div></div></section>
    <section className="section-space bg-white"><div className="container-page">
      <SectionTitle eyebrow="ScreenConnect Digital™" title="A proposed platform for pathway continuity and assurance." intro="ScreenConnect Digital™ is a proposed digital navigation and pathway-assurance platform designed to strengthen continuity between community and VCSE-led cancer engagement and established screening and referral pathways."/>
      <div className="mt-8 max-w-4xl space-y-5 text-lg leading-8 text-slate-700"><p>It is being developed to help programmes track progression from engagement to referral, screening and completed next steps; coordinate navigation support; identify pathway drop-off; and provide clearer outcome and inequalities reporting.</p><p>ScreenConnect Digital™ is intended to complement—not replace—clinical systems.</p></div>
      <aside className="screenconnect-discovery-callout mt-10" aria-labelledby="digital-discovery-title"><ShieldCheck aria-hidden="true" className="shrink-0 text-[#3858c7]" size={28}/><div><h3 id="digital-discovery-title">Digital innovation in discovery</h3><p>ScreenConnect Digital™ is currently at discovery and validation stage. BloomShield submitted the proposition to the NHS Innovation Service in September 2026 for needs assessment and support with pathway validation, product boundaries, governance, interoperability, pilot design and adoption planning.</p></div></aside>
    </div></section>
    <section className="section-space bg-[#f5f7ff]"><div className="container-page"><SectionTitle eyebrow="Two utilisation modes" title="Navigation support with clear clinical boundaries."/><div className="mt-12 grid gap-6 lg:grid-cols-2">{digitalModes.map(([title, items]) => <article key={title} className="screenconnect-card"><h3 className="font-display text-2xl font-semibold text-[#1d337d]">{title}</h3><List items={items}/></article>)}</div><p className="mt-7 max-w-4xl rounded-2xl border border-blue-900/10 bg-white p-6 leading-7 text-slate-700"><strong>NHS clinical systems remain authoritative</strong> for clinical information and decisions.</p></div></section>
    <section className="section-space"><div className="container-page"><SectionTitle eyebrow="Initial APP-002B focus" title="A focused route from engagement to measurable outcome." intro="The immediate product focus is community engagement → screening/referral → navigation → completed next step → measurable outcome. It does not propose to manage the full diagnosis, treatment or survivorship pathway."/><div className="mt-10 rounded-3xl border border-blue-900/10 bg-[#f5f7ff] p-6 sm:p-8"><p className="text-sm font-bold uppercase tracking-[.16em] text-[#3858c7]">Emerging design principle</p><p className="mt-4 font-display text-2xl font-semibold leading-snug text-[#1d337d] sm:text-3xl">Participant-reported <span aria-hidden="true">→</span> Navigator-confirmed <span aria-hidden="true">→</span> Provider-confirmed <span aria-hidden="true">→</span> System-verified</p><p className="mt-4 leading-7 text-slate-600">These proposed verification levels are an emerging design principle, not a statement that all four are currently implemented.</p></div></div></section>
    <section className="section-space bg-[#f5f7ff]"><div className="container-page"><SectionTitle eyebrow="Pathway continuity" title="How ScreenConnect Digital™ supports pathway continuity"/><div className="mt-10"><PathwayInfographic src="/images/screenconnect-digital-pathway-infographic.png" alt="ScreenConnect Digital pathway from community outreach and engagement through consent, barrier assessment, referral and appointment support, attendance or completion, next-step outcome, and navigation closure; it distinguishes community and navigator-led activity from NHS or provider-confirmed stages." caption="This illustration shows community-to-pathway handoffs, likely points of participant drop-off, milestone verification and the distinction between community/navigation activity and provider-confirmed pathway outcomes."/></div></div></section>
    <section className="section-space"><div className="container-page"><p className="mx-auto max-w-4xl rounded-2xl border border-blue-900/10 bg-[#f5f7ff] p-6 text-center leading-7 text-slate-700">A detailed ScreenConnect Digital™ discovery and product-development dossier is available to prospective NHS, research, commissioning and delivery partners on request.</p></div></section>
    <section className="section-space"><div className="container-page"><SectionTitle eyebrow="Where barriers occur" title="Cancer pathways contain multiple points where people can become disconnected from care." intro="Barriers to care can overlap and change over time. Identifying them early helps partners tailor navigation support to the person and the pathway."/><ul className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{barriers.map(item => <li key={item} className="flex items-center gap-3 rounded-2xl border border-blue-900/10 bg-white p-5 font-semibold text-slate-800 shadow-sm"><BellRing className="shrink-0 text-[#3858c7]" size={19}/>{item}</li>)}</ul></div></section>
    <section className="section-space bg-[#f5f7ff]"><div className="container-page"><SectionTitle eyebrow="Cancer care continuum" title="Supporting movement from prevention to survivorship." intro="The cancer care continuum describes the connected stages of prevention, screening, referral, diagnosis, treatment, follow-up and survivorship. ScreenConnect™ supports people to understand and move between these stages; clinical decisions and responsibility remain with qualified healthcare professionals and recognised services."/><ol className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-7">{continuum.map((item,index) => <li key={item} className="relative flex min-h-24 items-center justify-center rounded-2xl border border-blue-900/10 bg-white p-4 text-center font-display text-lg font-semibold text-[#1d337d] shadow-sm"><span className="sr-only">Stage {index + 1}: </span>{item}{index < continuum.length - 1 && <ArrowRight aria-hidden="true" className="absolute -right-4 z-10 hidden rounded-full bg-[#3858c7] p-1 text-white lg:block" size={28}/>}</li>)}</ol></div></section>
    <section className="section-space"><div className="container-page"><SectionTitle eyebrow="Why patient navigation matters" title="Navigation can strengthen continuity across complex cancer pathways." intro="Patient navigation does not replace clinical care. It helps people address barriers, understand next steps and remain connected to appropriate services."/><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-5">{navigationBenefits.map(({icon:Icon,title,summary}) => <article key={title} className="screenconnect-card p-6"><Icon aria-hidden="true" className="text-[#3858c7]" size={29}/><h3 className="mt-5 font-display text-xl font-semibold text-[#1d337d]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{summary}</p></article>)}</div></div></section>
    <section className="section-space bg-[#122864]"><div className="container-page grid gap-6 lg:grid-cols-2"><Purpose label="Vision" title="The right care, at the right time.">To create an intelligent and inclusive navigation ecosystem that keeps every person connected to the right care, at the right time, throughout the cancer journey.</Purpose><Purpose label="Mission" title="One connected pathway.">To reduce loss to follow-up by combining patient navigation, digital communication, care coordination, implementation data and community support within one connected pathway.</Purpose></div></section>
    <section className="section-space bg-[#f8f9ff]"><div className="container-page"><SectionTitle eyebrow="Five programme pillars" title="Human navigation supported by connected systems."/><div className="mt-12 grid gap-6 lg:grid-cols-2">{pillars.map(({icon:Icon,title,summary,items}, index) => <article key={title} className={`screenconnect-card ${index === 4 ? "lg:col-span-2" : ""}`}><div className="flex gap-5"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-[#3858c7] text-white"><Icon size={23}/></span><div><p className="text-xs font-bold uppercase tracking-widest text-[#5267c9]">Pillar {index + 1}</p><h3 className="mt-2 font-display text-2xl font-semibold text-[#1d337d]">{title}</h3><p className="mt-2 leading-7 text-slate-600">{summary}</p></div></div><div className="mt-6 flex flex-wrap gap-2">{items.map(item => <span key={item} className="rounded-full bg-[#edf0ff] px-4 py-2 text-sm font-semibold text-[#243c89]">{item}</span>)}</div></article>)}</div></div></section>
    <section className="section-space overflow-hidden bg-[#10245c] text-white"><div className="container-page"><p className="screenconnect-dark-eyebrow">Illustrative connected patient journey</p><h2 className="font-display text-4xl font-semibold sm:text-5xl">Barrier identification to survivorship—without losing the thread.</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-white/75">This sequence illustrates how patient navigation, tracking and follow-up may support an existing care pathway. Clinical responsibility remains with qualified healthcare professionals and recognised services.</p><ol className="screenconnect-journey mt-14">{journey.map((item,index) => <li key={item}><span>{index + 1}</span><p>{item}</p></li>)}</ol></div></section>
    <section className="section-space"><div className="container-page"><SectionTitle eyebrow="Clear scope" title="What ScreenConnect™ is—and what it is not."/><div className="mt-12 grid gap-6 lg:grid-cols-2"><article className="screenconnect-card"><h3 className="font-display text-3xl font-semibold text-[#1d337d]">ScreenConnect™ is</h3><List items={isItems}/></article><article className="screenconnect-card"><h3 className="font-display text-3xl font-semibold text-slate-700">ScreenConnect™ is not</h3><List items={isNotItems} negative/></article></div></div></section>
    <section className="section-space bg-[#f5f7ff]"><div className="container-page"><SectionTitle eyebrow="Potential supporting capabilities" title="Supporting delivery as ScreenConnect™ develops." intro="As ScreenConnect™ develops through discovery, co-design and evaluation, additional programme capabilities may support delivery. Their final form will depend on user need, pathway design, evidence and implementation requirements."/><div className="mt-12 grid gap-5 md:grid-cols-2">{future.map(([title,text,Icon]) => <article key={title} className="screenconnect-card"><Icon className="text-[#3858c7]" size={30}/><h3 className="mt-6 font-display text-2xl font-semibold text-[#1d337d]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>
    <section className="section-space"><div className="container-page"><SectionTitle eyebrow="Intended outcomes" title="Designed to support better continuity and coordination." intro="ScreenConnect™ aims to support these outcomes. Results will depend on context, delivery partners and the approaches agreed; no clinical or financial outcome is guaranteed."/><ul className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{outcomes.map(item => <li key={item} className="flex gap-3 rounded-2xl border border-blue-900/10 p-5 font-semibold"><CheckCircle2 className="mt-0.5 shrink-0 text-[#3858c7]" size={20}/>{item}</li>)}</ul></div></section>
    <section className="section-space bg-[#f8f9ff]"><div className="container-page"><SectionTitle eyebrow="BloomShield programme portfolio" title="Three distinct questions. One connected pathway."/><div className="mt-12 grid gap-6 lg:grid-cols-3"><Portfolio href="/programmes/screensmart-communities" accent="green" name="ScreenSmart Communities™" role="Builds awareness, confidence and demand for screening." question="Will people take action?"/><Portfolio href="/programmes/screenaccess" accent="coral" name="ScreenAccess™" role="Removes practical, geographic, financial and structural barriers to screening." question="Can people reach the service?"/><Portfolio href={path} accent="blue" name="ScreenConnect™" role="Supports navigation, referral completion, treatment and follow-up." question="Will people complete the pathway?"/></div><p className="mx-auto mt-12 max-w-3xl text-center font-display text-2xl font-semibold leading-10 text-[#1d337d]">ScreenSmart Communities™ inspires action.<br/>ScreenAccess™ enables access.<br/>ScreenConnect™ sustains the journey.</p></div></section>
    <section className="section-space bg-[#10245c] text-white"><div className="container-page"><p className="screenconnect-dark-eyebrow">CCPE implementation pathway</p><h2 className="font-display text-4xl font-semibold sm:text-5xl">Understand → Connect → Navigate → Evaluate → Scale</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-white/75">Aligned with BloomShield’s <Link href="/about#ccpe" className="font-bold text-blue-200 underline underline-offset-4">Cancer Care Partnership Ecosystem</Link>.</p><ol className="screenconnect-pathway mt-14">{implementation.map(([title,text],index) => <li key={title}><span>{index + 1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></div></section>
    <section className="section-space"><div className="container-page grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><SectionTitle eyebrow="Commissioning and partnership" title="Commission BloomShield&apos;s flagship patient-navigation programme." intro="ScreenConnect™ can be commissioned or developed in partnership for local, regional, national and international cancer pathways. Scope, delivery model, governance and evaluation measures are agreed with each commissioning partner."/><Link href={contactHref} className="screenconnect-link mt-8">Discuss a ScreenConnect™ Commission <ArrowRight size={17}/></Link></div><ul className="grid gap-3 sm:grid-cols-2">{partners.map(partner => <li key={partner} className="flex items-center gap-3 rounded-xl border border-blue-900/10 p-4 font-semibold"><Network className="shrink-0 text-[#3858c7]" size={19}/>{partner}</li>)}</ul></div></section>
    <section className="section-space bg-[#f5f7ff]"><div className="container-page grid gap-12 lg:grid-cols-2"><div><SectionTitle eyebrow="Programme development" title="Built carefully, tested collaboratively."/><p className="mt-6 text-lg leading-8 text-slate-700">ScreenConnect™ is intended to complement established services. Delivery models, communication channels, evaluation measures and governance will be agreed with partners and communities.</p><div className="mt-7 flex gap-4 rounded-2xl border-l-4 border-[#3858c7] bg-white p-6"><ShieldCheck className="mt-1 shrink-0 text-[#3858c7]"/><p className="leading-7 text-slate-700"><strong>Clinical responsibility:</strong> Diagnosis, treatment, urgent care and clinical judgement remain the responsibility of appropriately qualified professionals and recognised health services.</p></div></div><ProgrammeOverviewDownload programmeName="ScreenConnect™" pdfUrl={overviewPdf} theme="blue" volume={3} fileSize="22.03 MB" accessibleLabel="Download the ScreenConnect programme overview PDF" /></div></section>
    <section className="screenconnect-closing"><div className="container-page relative py-20 text-center sm:py-24"><p className="screenconnect-dark-eyebrow">Connecting the pathway</p><h2 className="mx-auto max-w-4xl font-display text-4xl font-semibold sm:text-5xl">No one should be lost between screening and treatment.</h2><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-white/80">Work with BloomShield to explore a human, inclusive and evidence-informed approach to patient navigation and care coordination.</p><Link href={contactHref} className="screenconnect-primary-button mt-9">Discuss a ScreenConnect™ Partnership <ArrowRight aria-hidden="true" size={17}/></Link></div></section>
  </>;
}

function Purpose({label,title,children}:{label:string;title:string;children:string}) {
  return <article className="screenconnect-purpose-card rounded-3xl border p-8 sm:p-10"><p className="screenconnect-eyebrow">{label}</p><h2 className="font-display text-3xl font-semibold text-[#14265b]">{title}</h2><p className="mt-5 text-lg leading-8 text-slate-700">{children}</p></article>;
}
function ProgrammeStatement({href,accent,icon:Icon,name,statement}:{href:string;accent:"green"|"coral"|"blue";icon:LucideIcon;name:string;statement:string}) {
  return <Link href={href} className={`screenconnect-programme-link screenconnect-programme-link-${accent}`}><span className="screenconnect-programme-link-icon"><Icon aria-hidden="true" size={22}/></span><span className="min-w-0"><strong className="block font-display text-xl leading-7">{name}</strong><span className="block text-base leading-7 text-slate-700">{statement}</span></span><ArrowRight aria-hidden="true" className="ml-auto shrink-0" size={21}/></Link>;
}
function Portfolio({href,accent,name,role,question}:{href:string;accent:"green"|"coral"|"blue";name:string;role:string;question:string}) {
  const colours = {green:"border-emerald-600 bg-emerald-50 text-emerald-950",coral:"border-[#c8583c] bg-[#fff3ee] text-[#71301f]",blue:"border-[#3858c7] bg-[#edf0ff] text-[#1d337d]"};
  return <article className={`rounded-3xl border-t-4 p-7 ${colours[accent]}`}><Link href={href} className="font-display text-2xl font-semibold underline decoration-2 underline-offset-4">{name}</Link><p className="mt-5 leading-7">{role}</p><p className="mt-6 text-sm font-bold uppercase tracking-wider">Core question</p><p className="mt-2 font-display text-xl font-semibold">{question}</p></article>;
}
