import { ArrowRight, CheckCircle2, Compass, DoorOpen, Network, Presentation, ScanLine, Waypoints } from "lucide-react";
import Link from "next/link";
import { CTA } from "@/components/cta";
import { PageHero } from "@/components/page-hero";
import { SectionHeading } from "@/components/section-heading";
import { PageStructuredData } from "@/components/seo-json-ld";
import { createMetadata } from "@/lib/seo";

const description = "Explore BloomShield's flagship cancer prevention programmes: ScreenSmart Communities, ScreenAccess and ScreenConnect.";
export const metadata = createMetadata({ title: "Cancer Prevention Programmes", description, path: "/programmes" });

export default function Programmes() {
  return <>
    <PageStructuredData name="Cancer Prevention Programmes" description={description} path="/programmes" breadcrumb="Programmes" />
    <PageHero visual="programmes" eyebrow="BloomShield flagship product family" title="Three programmes. One pathway to fairer prevention." intro="ScreenSmart Communities™, ScreenAccess™ and ScreenConnect™ form a cohesive family of community-led, evidence-informed implementation models." cta="Discuss a programme"/>

    <section id="screen-smart" className="section-space scroll-mt-24"><div className="container-page"><div className="relative overflow-hidden rounded-4xl bg-gradient-to-br from-[#061f35] via-[#073f4b] to-[#096b70] p-8 text-white shadow-[0_35px_85px_-40px_rgba(6,31,53,.75)] sm:p-12"><div aria-hidden="true" className="absolute -right-24 -top-24 h-80 w-80 rounded-full border-[54px] border-emerald-300/10"/><div className="relative grid gap-12 lg:grid-cols-2"><div><span className="inline-flex rounded-full border border-[#64e3d2]/30 bg-[#64e3d2]/10 px-4 py-2 text-xs font-bold uppercase tracking-[.18em] text-[#8ff2df]">Flagship delivery programme</span><h2 className="mt-7 font-display text-4xl font-semibold sm:text-5xl">ScreenSmart Communities™</h2><p className="mt-5 max-w-xl text-lg leading-8 text-white/80">A flexible delivery model for working with communities and health systems to improve screening understanding, informed choice and access.</p><p className="mt-5 text-sm font-bold uppercase tracking-widest text-[#8ff2df]">Community insight → trusted engagement → action</p><Link href="/contact" className="mt-9 inline-flex items-center gap-2 font-bold underline decoration-[#64e3d2] decoration-2 underline-offset-8">Bring ScreenSmart to your area <ArrowRight size={17}/></Link></div><div className="grid gap-3">{[["01","Understand local barriers and assets","bg-[#0a4a57]"],["02","Co-design culturally relevant engagement","bg-[#0b5e68]"],["03","Equip trusted community messengers","bg-[#0d7277]"],["04","Create clear navigation into services","bg-[#118687]"],["05","Evaluate reach, experience and learning","bg-[#239b96]"]].map(([n,x,c])=><div className={`group flex items-center gap-4 rounded-2xl ${c} p-4 shadow-sm transition hover:translate-x-1 hover:shadow-md`} key={x}><span className="text-xs font-bold text-white/55">{n}</span><CheckCircle2 className="shrink-0 text-[#8ff2df]" size={20}/><span className="font-semibold">{x}</span></div>)}</div></div></div></div></section>

    <section className="section-space bg-gradient-to-b from-mist to-white"><div className="container-page"><SectionHeading eyebrow="Flagship innovations" title="Access and connection—designed as implementation products." intro="Each programme solves a distinct challenge while sharing BloomShield’s commitment to equity, evidence, community leadership and scalable delivery."/><div className="mt-14 grid gap-8 lg:grid-cols-2">
      <article id="screen-access" className="group relative min-h-[540px] scroll-mt-24 overflow-hidden rounded-[2.5rem] border border-[#d96748]/30 bg-gradient-to-br from-[#fff8f3] via-[#fde8dc] to-[#f9d2c2] p-9 shadow-[0_35px_80px_-42px_rgba(169,67,45,.55)] transition hover:-translate-y-1 hover:shadow-[0_42px_90px_-40px_rgba(169,67,45,.62)] sm:p-12"><div aria-hidden="true" className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-[#e88768]/20"/><div aria-hidden="true" className="absolute -bottom-24 -left-16 h-60 w-60 rounded-full border-[40px] border-[#d96748]/10"/><div className="relative flex h-full flex-col"><span className="flex h-20 w-20 items-center justify-center rounded-[1.6rem] bg-gradient-to-br from-[#d96748] to-[#a9432d] text-white shadow-xl"><DoorOpen className="h-10 w-10"/></span><p className="mt-10 text-xs font-bold uppercase tracking-[.18em] text-[#a9432d]">Flagship innovation</p><h2 className="mt-3 font-display text-4xl font-semibold tracking-tight text-[#74301f] sm:text-5xl">ScreenAccess™</h2><h3 className="mt-5 font-display text-2xl font-semibold text-[#74301f]">Make barriers visible. Make access possible.</h3><p className="mt-5 max-w-xl text-lg leading-8 text-[#71483e]">A structured model for understanding where people encounter friction across awareness, invitation, booking, attendance and follow-up—and co-designing practical improvements.</p><div className="mt-auto flex items-center gap-3 border-t border-[#a9432d]/20 pt-7 text-base font-bold text-[#923a26]"><Compass className="h-6 w-6"/>Turning barrier insights into practical action.</div></div></article>

      <article id="screen-connect" className="group relative min-h-[540px] scroll-mt-24 overflow-hidden rounded-[2.5rem] border border-[#4f61cd]/30 bg-gradient-to-br from-[#f7f8ff] via-[#e7e9ff] to-[#d8dcff] p-9 shadow-[0_35px_80px_-42px_rgba(64,81,181,.55)] transition hover:-translate-y-1 hover:shadow-[0_42px_90px_-40px_rgba(64,81,181,.62)] sm:p-12"><div aria-hidden="true" className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-[#5968c9]/20"/><div aria-hidden="true" className="absolute -bottom-24 -left-16 h-60 w-60 rounded-full border-[40px] border-[#4051b5]/10"/><div className="relative flex h-full flex-col"><span className="flex h-20 w-20 items-center justify-center rounded-[1.6rem] bg-gradient-to-br from-[#5267dc] to-[#30439f] text-white shadow-xl"><Waypoints className="h-10 w-10"/></span><p className="mt-10 text-xs font-bold uppercase tracking-[.18em] text-[#4051b5]">Flagship innovation</p><h2 className="mt-3 font-display text-4xl font-semibold tracking-tight text-[#293474] sm:text-5xl">ScreenConnect™</h2><h3 className="mt-5 font-display text-2xl font-semibold text-[#293474]">Strengthen trusted routes to screening.</h3><p className="mt-5 max-w-xl text-lg leading-8 text-[#4a4f73]">A partnership model connecting community organisations, primary care and screening services so information, support and onward routes are clearer and more coordinated.</p><div className="mt-auto flex items-center gap-3 border-t border-[#4051b5]/20 pt-7 text-base font-bold text-[#34459f]"><Network className="h-6 w-6"/>Coordination, partnership and navigation.</div></div></article>
    </div></div></section>

    <section className="section-space"><div className="container-page"><SectionHeading eyebrow="Future initiatives" title="A responsible pipeline, shaped by need." intro="Future work will be developed with communities and partners, moving forward only where there is a clear public benefit and a credible path to delivery."/><div className="mt-10 grid gap-5 sm:grid-cols-3"><div className="rounded-2xl border p-6"><Presentation className="text-teal-600"/><h3 className="mt-5 font-bold">Community prevention academy</h3><p className="mt-2 text-slate-600">Training for trusted messengers and frontline teams.</p></div><div className="rounded-2xl border p-6"><ScanLine className="text-teal-600"/><h3 className="mt-5 font-bold">Inclusive digital navigation</h3><p className="mt-2 text-slate-600">Accessible tools that support, rather than replace, human care.</p></div><div className="rounded-2xl border p-6"><Network className="text-teal-600"/><h3 className="mt-5 font-bold">Learning collaboratives</h3><p className="mt-2 text-slate-600">Shared learning across places and prevention pathways.</p></div></div></div></section>
    <CTA/>
  </>;
}
