import Link from "next/link";
import { ArrowRight, BrainCircuit, HeartHandshake, Microscope, ShieldCheck, UsersRound } from "lucide-react";
import { CTA } from "@/components/cta";
import { HomeEmblem } from "@/components/home-emblem";
import { SectionHeading } from "@/components/section-heading";

const pillars = [
  { icon: UsersRound, title: "Community-led prevention", text: "We listen, co-design and work with trusted local voices so prevention feels relevant, respectful and reachable." },
  { icon: Microscope, title: "Implementation science", text: "We connect evidence, context and delivery so proven ideas can work across real communities and health systems." },
  { icon: BrainCircuit, title: "Responsible innovation", text: "We explore digital health and AI with equity, safety and human connection built in from the start." }
];

export default function Home() {
  return <>
    <section className="relative overflow-hidden bg-gradient-to-br from-white via-teal-50 to-emerald-400/10">
      <div aria-hidden="true" className="absolute right-[-8rem] top-[-9rem] hidden h-[32rem] w-[32rem] rounded-full border-[80px] border-white/60 lg:block"/>
      <div className="container-page grid min-h-[720px] items-center gap-12 py-20 lg:grid-cols-[1.08fr_.92fr]">
        <div><p className="eyebrow">Cancer prevention, powered by communities</p><h1 className="display max-w-3xl">Protect lives.<br/>Prevent cancer.<br/><span className="text-teal-600">Empower communities.</span></h1><p className="lead mt-7 max-w-xl">BloomShield combines community insight, implementation science and evidence-informed partnerships to advance equitable cancer prevention across diverse communities and health systems.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/programmes" className="button-primary">Explore our programmes <ArrowRight size={17}/></Link><Link href="/partnerships" className="button-secondary">Partner with us</Link></div></div>
        <HomeEmblem />
      </div>
    </section>
    <div className="border-y border-teal-900/10 bg-white"><div className="container-page grid gap-px py-5 text-center text-xs font-bold uppercase tracking-[.14em] text-teal-800 sm:grid-cols-3"><p className="py-2">Multi-country implementation experience</p><p className="border-teal-900/10 py-2 sm:border-x">Evidence-informed partnerships</p><p className="py-2">International collaborations</p></div></div>

    <section className="section-space"><div className="container-page"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><SectionHeading eyebrow="Why BloomShield" title="Prevention should work for everyone." intro="Too often, the people at greatest risk face the greatest barriers to information, screening and timely support. BloomShield exists to help close that gap."/><div className="grid gap-5 sm:grid-cols-2"><div className="card"><HeartHandshake className="text-teal-600"/><h3 className="mt-6 text-xl font-bold">Built with communities</h3><p className="mt-3 leading-7 text-slate-600">Local knowledge shapes our priorities, language and delivery—not just our feedback forms.</p></div><div className="card sm:translate-y-8"><ShieldCheck className="text-teal-600"/><h3 className="mt-6 text-xl font-bold">Designed for adoption</h3><p className="mt-3 leading-7 text-slate-600">We plan for sustainable implementation from day one, working within real-world systems and constraints.</p></div></div></div></div></section>

    <section className="section-space bg-mist"><div className="container-page"><SectionHeading eyebrow="Our three pillars" title="Care, evidence and progress—working together."/><div className="mt-12 grid gap-6 md:grid-cols-3">{pillars.map(({icon:Icon,title,text},i)=><article key={title} className="rounded-3xl bg-white p-8"><span className="font-display text-sm font-bold text-gold-500">0{i+1}</span><Icon className="mt-8 h-8 w-8 text-teal-600"/><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>

    <section className="section-space"><div className="container-page"><SectionHeading eyebrow="Flagship programme" title="ScreenSmart Communities™" intro="A community-centred approach to improving cancer awareness, informed choice and access to screening."/><div className="mt-12 grid overflow-hidden rounded-4xl bg-[#062f3b] text-white lg:grid-cols-2"><div className="p-8 sm:p-12"><p className="text-sm font-bold uppercase tracking-widest text-emerald-400">Awareness → confidence → action</p><h3 className="mt-5 font-display text-3xl font-semibold">Screening conversations that begin with trust.</h3><p className="mt-5 leading-7 text-white/70">ScreenSmart Communities™ works alongside local organisations and health partners to understand barriers, strengthen knowledge and create clearer routes into screening.</p><Link href="/programmes" className="mt-8 inline-flex items-center gap-2 font-bold text-white underline decoration-emerald-400 decoration-2 underline-offset-8">Discover the programme <ArrowRight size={17}/></Link></div><div className="grid gap-2 p-5 sm:grid-cols-2">{[["Listen","Community insight","bg-[#0b4650]"],["Design","Co-design","bg-[#0d5960]"],["Equip","Trusted messengers","bg-[#0e6c70]"],["Connect","Service navigation","bg-[#147f7d]"],["Learn","Evaluation","bg-[#25958d] sm:col-span-2"]].map(([step,label,colour])=><div key={step} className={`rounded-2xl ${colour} p-5 transition-transform hover:-translate-y-0.5`}><p className="text-xs font-bold uppercase tracking-widest text-white/65">{step}</p><p className="mt-2 text-lg font-semibold">{label}</p></div>)}</div></div></div></section>

    <section className="section-space border-y border-teal-900/10 bg-teal-50"><div className="container-page"><SectionHeading eyebrow="How we define impact" title="Progress we can see, learn from and sustain." intro="We do not publish unverified headline statistics. Our work is designed around transparent, programme-specific measures."/><div className="mt-10 grid gap-6 sm:grid-cols-3"><div><p className="text-2xl font-semibold text-teal-700">Reach</p><p className="mt-2 text-slate-600">Who is engaged, and who is still missing?</p></div><div><p className="text-2xl font-semibold text-teal-700">Experience</p><p className="mt-2 text-slate-600">Do people feel informed, respected and able to act?</p></div><div><p className="text-2xl font-semibold text-teal-700">System change</p><p className="mt-2 text-slate-600">What improves in pathways, practice and partnership?</p></div></div></div></section>

    <section className="section-space"><div className="container-page"><SectionHeading align="center" eyebrow="Evidence-informed partnerships" title="Better prevention is a shared endeavour." intro="We connect communities, health systems, research and innovation partners across countries—keeping public benefit and implementation at the centre."/><div className="mt-10 grid grid-cols-2 gap-3 text-center text-sm font-bold text-slate-600 sm:grid-cols-3 lg:grid-cols-6">{["Communities","Health systems","Universities","Charities","Innovators","International partners"].map(x=><div key={x} className="flex min-h-24 items-center justify-center rounded-2xl border border-teal-900/10 bg-gradient-to-br from-white to-teal-50 px-3 shadow-sm">{x}</div>)}</div></div></section>

    <section className="section-space bg-mist"><div className="container-page"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><SectionHeading eyebrow="Latest insights" title="Ideas for more equitable prevention."/><Link href="/research-innovation" className="inline-flex items-center gap-2 font-bold text-teal-700">Explore research <ArrowRight size={17}/></Link></div><div className="mt-10 grid gap-6 md:grid-cols-3">{[
      ["Implementation science","Why good evidence is only the beginning","Closing the gap between what we know and what communities experience."],
      ["Community engagement","Trust is part of the intervention","Meaningful engagement changes programme design, not just programme language."],
      ["Responsible innovation","Equity before automation","Questions every health AI programme should ask before implementation."]
    ].map(([tag,title,text])=><article className="card" key={title}><p className="text-xs font-bold uppercase tracking-widest text-teal-600">{tag}</p><h3 className="mt-5 text-xl font-bold leading-snug">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>
    <CTA/>
  </>;
}
