import Link from "next/link";
import { InsightsShell } from "@/components/insights-shell";
import { BreastCancerAwarenessCollection } from "@/components/breast-cancer-awareness-collection";
import { InsightsCollectionStructuredData } from "@/components/insights-structured-data";
import { createInsightMetadata } from "@/lib/seo";
import { conversationsSeries, insights, partnershipPlaybook } from "@/lib/insights";
const description="Connected editorial collections exploring equitable cancer prevention, screening and care.";
const articles=insights.filter(item=>item.area==="Series & Collections" && item.status==="published");
export const metadata=createInsightMetadata({title:"Series & Collections | BloomShield Insights",description,path:"/insights/series-collections",socialImage:"/images/insights/breast-cancer-awareness-before-gaps-card.png",socialImageAlt:"BloomShield Breast Cancer Awareness Month",socialImageWidth:1254,socialImageHeight:1254});
export default function SeriesCollectionsPage(){return <InsightsShell><InsightsCollectionStructuredData title="Series & Collections" description={description} path="/insights/series-collections" image="/images/insights/breast-cancer-awareness-before-gaps-card.png" keywords={["Breast Cancer Awareness Month","Equitable Cancer Care"]} items={articles.map(article=>({name:article.title,url:article.href!}))}/><div className="container-page py-14 md:py-20"><Link href="/insights" className="font-bold text-teal-700">← All Insights</Link><p className="eyebrow mt-10">BloomShield Insights</p><h1 className="heading mt-4">Series &amp; Collections</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-600">{description}</p><BreastCancerAwarenessCollection/><section className="mt-12 rounded-[2rem] border border-teal-900/10 p-8"><h2 className="font-display text-3xl font-semibold">{conversationsSeries.title}</h2><p className="mt-5 text-lg leading-8 text-slate-600">{conversationsSeries.description}</p><Link href={conversationsSeries.href} className="mt-6 inline-block font-bold text-teal-700">Explore Conversations →</Link></section><section className="mt-8 rounded-[2rem] border border-teal-900/10 p-8"><p className="eyebrow">Foundational archive</p><h2 className="mt-4 font-display text-3xl font-semibold">{partnershipPlaybook.title}</h2><p className="mt-5 text-lg leading-8 text-slate-600">{partnershipPlaybook.description}</p><p className="mt-6 font-bold text-teal-700">9 article slots prepared</p></section></div></InsightsShell>}
