import type { Metadata } from "next";
import Link from "next/link";
import { InsightArticle } from "@/components/insight-article";
import { getInsightAuthors, insightPublisher, insights } from "@/lib/insights";
import { createInsightMetadata, ORGANIZATION_NAME, SITE_URL } from "@/lib/seo";

const article = insights.find(item => item.slug === "australia-world-eliminating-cervical-cancer")!;
const authors = getInsightAuthors(article);
const path = "/insights/evidence-policy/australia-world-eliminating-cervical-cancer";
const standfirst = "Australia is on track to eliminate cervical cancer as a public-health problem by 2035. Its greatest lesson for the rest of the world may not be a vaccine or a screening test — but how evidence, policy, infrastructure and implementation were brought together.";
const seoTitle = article.seoTitle ?? article.title;
const seoDescription = article.seoDescription ?? article.description;
const canonicalPath = article.canonicalUrl ?? path;
const socialImage = article.socialImage ?? article.image!;
const socialImageAlt = article.socialImageAlt ?? article.imageAlt!;
const keywords = article.keywords ?? article.tags ?? [];

export const metadata: Metadata = createInsightMetadata({
  title: seoTitle,
  description: seoDescription,
  path: canonicalPath,
  socialImage,
  socialImageAlt,
  socialImageWidth: article.socialImageWidth ?? 1672,
  socialImageHeight: article.socialImageHeight ?? 941,
  socialImageType: article.socialImageType,
  socialTitle: article.socialTitle,
  socialDescription: article.socialDescription,
  type: "article",
  keywords,
  authors: authors.map(author => author.name),
  datePublished: article.datePublished ?? article.publishedAtIso,
  dateModified: article.dateModified ?? article.publishedAtIso,
});

const references = [
  { label: "Cervical Cancer Elimination Initiative", source: "World Health Organization", href: "https://www.who.int/initiatives/cervical-cancer-elimination-initiative" },
  { label: "National Strategy for the Elimination of Cervical Cancer in Australia", source: "Australian Government Department of Health, Disability and Ageing, 2023", href: "https://www.health.gov.au/resources/publications/national-strategy-for-the-elimination-of-cervical-cancer-in-australia" },
  { label: "Australia on track to eliminate cervical cancer by 2035", source: "Australian Government Department of Health, Disability and Ageing, 19 November 2025", href: "https://www.health.gov.au/ministers/the-hon-rebecca-white-mp/media/australia-on-track-to-eliminate-cervical-cancer-by-2035" },
  { label: "National Cervical Screening Program monitoring report 2025", source: "Australian Institute of Health and Welfare, 2025", href: "https://www.aihw.gov.au/reports/cancer-screening/ncsp-monitoring-report-2025/contents/summary" },
  { label: "About the National Cervical Screening Program", source: "National Cancer Screening Register", href: "https://www.ncsr.gov.au/cervical-program" },
  { label: "The projected timeframe until cervical cancer elimination in Australia: a modelling study", source: "Hall MT, Simms KT, Lew J-B, et al. The Lancet Public Health, 2019; 4:e19–e27", href: "https://doi.org/10.1016/S2468-2667(18)30183-X" },
];

const relatedContent = <section aria-labelledby="related-insights">
  <h2 id="related-insights">Related Insights</h2>
  <div className="mt-6 rounded-[1.5rem] border border-teal-900/10 bg-white p-6">
    <p className="text-xs font-bold uppercase tracking-[.16em] text-teal-700">Evidence &amp; Policy</p>
    <h3 className="mt-3 font-display text-2xl font-semibold">HPV Self-Testing Is a Major Step Forward — But Will It Close the Screening Gap?</h3>
    <p className="mt-3 leading-7 text-slate-600">What England’s national HPV self-testing offer reveals about access, follow-up and equitable pathway completion.</p>
    <Link href="/insights/evidence-policy/hpv-self-testing-screening-gap" data-insights-event="insights_related_content_click" className="mt-5 inline-flex font-bold text-teal-700 underline decoration-teal-700/30 underline-offset-4">Read the Insight</Link>
  </div>
</section>;

export default function AustraliaWorldInsightPage() {
  const jsonLd = {
    "@context": "https://schema.org", "@type": "BlogPosting", "@id": `${SITE_URL}${canonicalPath}#article`, headline: article.title, alternativeHeadline: standfirst, description: seoDescription,
    image: { "@type": "ImageObject", url: `${SITE_URL}${socialImage}`, width: article.socialImageWidth, height: article.socialImageHeight, caption: socialImageAlt },
    datePublished: article.datePublished, dateModified: article.dateModified,
    author: authors.map(author => ({ "@type": "Person", name: author.name, description: author.biography, ...(author.credentials ? { jobTitle: author.credentials } : {}), affiliation: { "@type": "Organization", name: "BloomShield CIC", url: SITE_URL } })),
    publisher: { "@type": "Organization", name: insightPublisher.name, url: `${SITE_URL}/insights`, parentOrganization: { "@type": "Organization", name: ORGANIZATION_NAME, url: SITE_URL }, logo: { "@type": "ImageObject", url: `${SITE_URL}/bloomshield-square-lockup.png`, width: 545, height: 590 } },
    mainEntityOfPage: { "@type": "WebPage", "@id": `${SITE_URL}${canonicalPath}` }, articleSection: article.area, keywords: keywords.join(", "), about: keywords.map(name => ({ "@type": "Thing", name })), inLanguage: "en-GB",
  };

  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} />
    <InsightArticle category={article.area} crossTag="Implementation & Equity" title={article.title} articleSlug={article.slug} date={article.publishedAt!} dateIso={article.publishedAtIso!} authors={authors} publisher={insightPublisher.name} standfirst={standfirst} image={article.image!} imageAlt={article.imageAlt!} heroClassName="aspect-[1419/710]" domains={["People", "Partnerships", "Systems", "Innovation", "Equity", "Impact"]} ccpeLens={article.ccpeLens} tags={article.tags} reflectionQuestion={article.reflectionQuestion} linkedinDiscussionUrl={article.linkedinDiscussionUrl} linkedinDiscussionTitle="Continue the conversation" linkedinDiscussionDescription="This perspective is also being discussed on LinkedIn. Join the conversation, share your perspective, and follow the next instalments in our Australia → World cervical cancer elimination series." linkedinDiscussionLinkLabel="Join the discussion on LinkedIn →" references={references} referencesHeading="Sources & further reading" relatedContent={relatedContent} implementationLesson={<p>Elimination is not delivered by a vaccine, a screening test or a policy alone. Its public-health value depends on the pathway between them: accessible services, reliable data, follow-up, treatment, equity and the capacity to adapt as evidence changes.</p>} previous={{ label: "HPV self-testing and the screening gap", href: "/insights/evidence-policy/hpv-self-testing-screening-gap" }} next={{ label: "Conversations Across the Cancer Care Ecosystem", href: "/insights/conversations" }}>
      <section aria-labelledby="australia-moving">
        <p id="australia-moving">Australia is moving towards something extraordinary.</p>
        <p>In 2025, the Australian Government reported that the country remained on track to eliminate cervical cancer as a public-health problem by 2035.</p>
        <p>But perhaps the most interesting question for the rest of the world is not simply whether Australia gets there.</p><p>It is how.</p><p>Because Australia’s progress is not the story of one breakthrough.</p><p>Not one vaccine.</p><p>Not one screening test.</p><p>Not one awareness campaign.</p><p>It is the story of a system.</p>
      </section>
      <section aria-labelledby="elimination-meaning"><h2 id="elimination-meaning">What does “elimination” actually mean?</h2><p>Eliminating cervical cancer does not mean that no Australian woman will ever develop the disease again.</p><p>The World Health Organization defines cervical cancer elimination as reducing incidence below 4 cases per 100,000 women per year and maintaining it there.</p><p>Its global strategy is built around the 90–70–90 targets:</p><ul><li>90% of girls fully vaccinated against HPV by age 15;</li><li>70% of women screened using a high-performance test by ages 35 and 45; and</li><li>90% of women identified with cervical disease receiving appropriate treatment.</li></ul><p>Australia has not yet crossed the elimination threshold. But decades of coordinated prevention have brought it remarkably close.</p><p>And understanding how that happened matters.</p></section>
      <section aria-labelledby="journey"><h2 id="journey">The journey started long before elimination became the goal</h2><p>Australia established its organised National Cervical Screening Program in 1991.</p><p>Then came another transformative intervention.</p><p>In 2007, Australia introduced a national HPV vaccination programme for girls, later extending vaccination to boys.</p><p>Vaccination began changing the future risk of cervical cancer across an entire generation.</p><p>But vaccination could not protect every woman already exposed to HPV.</p><p>Screening therefore remained essential.</p><p>In December 2017, Australia fundamentally redesigned its cervical screening programme, moving from two-yearly cytology to five-yearly primary HPV testing for eligible people aged 25–74.</p><p>Then, in 2022, another important change followed.</p><p>HPV self-collection became available to everyone eligible for cervical screening.</p><p>That decision matters because barriers to cervical screening are not purely medical.</p><p>Fear of examination, previous trauma, embarrassment, cultural concerns, geography, inconvenience and difficulty accessing services can all determine whether an invitation becomes actual participation.</p><p>Self-collection changes that relationship.</p><p>Instead of repeatedly asking why people do not participate in the existing system, it asks whether the system itself can change.</p><p>That is implementation thinking.</p></section>
      <section aria-labelledby="infrastructure"><h2 id="infrastructure">The invisible infrastructure matters</h2><p>Vaccines and HPV tests attract attention.</p><p>Registers rarely do.</p><p>Yet behind Australia’s cervical cancer progress sits something less visible and arguably just as important: organised screening infrastructure.</p><p>The National Cancer Screening Register helps support screening histories, reminders and follow-up.</p><p>That matters because cancer prevention is not simply an encounter between a person and a test.</p><p>Someone needs to know who is eligible. Someone needs to invite them. The result needs to be recorded. An abnormal result must trigger an appropriate next step. People requiring surveillance need to be recalled. Those requiring colposcopy or treatment must not disappear between organisational boundaries. And programmes need to know whether any of this actually happened.</p><p className="insight-pull-statement">A screening programme is not a collection of tests. It is a pathway.</p></section>
      <section aria-labelledby="evidence-policy"><h2 id="evidence-policy">Evidence did not simply observe policy — it helped shape it</h2><p>Australia’s cervical cancer story also demonstrates the value of a close relationship between research, modelling and policy.</p><p>A landmark modelling study led by Michaela Hall and colleagues, including Professor Marion Saville and Professor Karen Canfell, projected that Australia could cross the WHO elimination threshold around 2028, although the uncertainty interval extended as far as 2035.</p><p>The important point is not the precise predicted year.</p><p>It is the process.</p><p>Researchers modelled possible futures. Programmes changed. Population data monitored what happened. Evidence accumulated. Policy continued to evolve.</p><p className="insight-pull-statement">Evidence → policy → implementation → measurement → adaptation.</p><p>Australia did not create a screening programme decades ago and simply leave it running. The technology changed. The epidemiology changed. The evidence changed. And the programme changed with them.</p></section>
      <section aria-labelledby="equity"><h2 id="equity">But there is another Australian story</h2><p>National averages can conceal inequality.</p><p>And Australia’s cervical cancer elimination story is not yet an equitable elimination story.</p><p>Aboriginal and Torres Strait Islander women continue to experience substantially higher cervical cancer incidence and mortality than non-Indigenous women.</p><p>Recent Australian data also show concerning falls in HPV vaccination coverage, including among Aboriginal and Torres Strait Islander girls.</p><p>That creates an uncomfortable but essential question:</p><p className="insight-question-line">When can a country truly claim success if particular communities continue to carry a disproportionate burden of a preventable cancer?</p><p>Australia’s own National Strategy for the Elimination of Cervical Cancer recognises this.</p><p>Its ambition is not simply elimination.</p><p>It is equitable elimination.</p><p>That means culturally safe services, community-led approaches, partnerships with Aboriginal Community Controlled Health Organisations, better access and deliberate attention to populations that national averages can leave behind.</p><p>The final kilometres towards elimination may therefore prove harder than the first.</p><p>And they may teach the world just as much.</p></section>
      <section aria-labelledby="global-lessons"><h2 id="global-lessons">What can Africa and other health systems learn?</h2><p>This is where interpretation matters.</p><p>Australia cannot simply be copied and pasted into Nigeria, Kenya, Zimbabwe, Tanzania or other African settings.</p><p>Health systems differ. Fiscal capacity differs. Laboratory infrastructure differs. Population registers differ. Workforce availability differs. Geography differs. Screening may remain opportunistic rather than organised. Access to pathology, colposcopy and treatment may be limited.</p><p>The lesson is not:</p><p className="insight-question-line">Copy Australia.</p><p>It is:</p><p className="insight-question-line">Copy the architecture, not necessarily the machinery.</p><p>Five lessons stand out.</p><h3>1. Prevention must operate as a pathway</h3><p>Vaccination protects future generations. Screening identifies present risk. Diagnosis confirms disease. Treatment prevents progression or treats cancer. If people disappear between those stages, even excellent individual technologies will fail to deliver their full population benefit.</p><h3>2. Design screening around people</h3><p>Australia’s self-collection experience illustrates an important principle. When embarrassment, trauma, culture, geography or inconvenience prevent participation, changing how screening is delivered can be as important as changing the screening technology.</p><p>Health systems should not endlessly ask why communities fail to fit their services. Sometimes the service needs to change.</p><h3>3. Build the information architecture</h3><p>Registers, reminders and follow-up systems may appear less innovative than AI or molecular diagnostics. But every effective screening programme needs to answer several deceptively simple questions:</p><div className="my-8 rounded-[1.5rem] bg-teal-50 p-7 font-semibold leading-8 text-teal-900"><p className="!mt-0">Who was eligible? Who was reached? Who was screened? What was the result? What should happen next? Did it happen? Who was lost along the pathway?</p></div><p>Without those answers, screening activity is not the same thing as a screening system.</p><h3>4. Allow evidence to change policy</h3><p>Programmes should evolve. New evidence, technologies and patterns of participation should inform how services are designed and delivered.</p><p>Australia’s transition from cytology to primary HPV testing and then to universal self-collection demonstrates that adaptability.</p><h3>5. Measure equity separately from national success</h3><p>A national average can improve while particular populations remain behind. That is why elimination cannot simply be a national statistical achievement. It must also ask who benefited.</p><p>This principle applies just as readily in Lagos, London or Lusaka as it does in Sydney.</p></section>
      <section aria-labelledby="architecture"><p id="architecture" className="insight-pull-statement">The technology may be different. The architecture still matters.</p><p>African cervical cancer elimination strategies will not necessarily resemble Australia’s operational model. Nor should they.</p><p>Single-dose HPV vaccination, community-based delivery, HPV self-sampling, decentralised testing, portable treatment technologies, task-sharing, telemedicine and digital navigation may play particularly important roles.</p><p>The precise configuration should reflect local realities.</p><p>But the connections still matter:</p><div className="my-8 border-l-2 border-[#b9892f] pl-5 font-display text-xl font-semibold leading-8 text-ink sm:pl-6"><p className="!mt-0">Vaccination → screening → diagnosis → treatment.</p><p>Communities → services.</p><p>Data → follow-up.</p><p>Evidence → policy.</p><p>Policy → measurable outcomes.</p></div><p>The technologies can change. The need for a functioning pathway does not.</p></section>
      <section aria-labelledby="biggest-lesson"><h2 id="biggest-lesson">Perhaps the biggest lesson is not about cervical cancer at all</h2><p>We already possess many of the scientific tools required to prevent cervical cancer.</p><p>HPV vaccines exist. High-performance HPV tests exist. Precancerous lesions can be identified and treated.</p><p>The difficult work lies between scientific discovery and population outcome.</p><p>It lies in policy, financing, workforce, implementation, community trust, information systems, navigation, follow-up, treatment, measurement and continuous adaptation.</p><p>That is why Australia’s progress should be understood as more than a vaccination or screening success.</p><p>It is an implementation story.</p><p>And that is precisely why the rest of the world should pay attention.</p></section>
      <section aria-labelledby="conversation-continues"><h2 id="conversation-continues">The conversation continues</h2><p>BloomShield Insights will continue exploring the people, evidence and systems behind cervical cancer elimination — including what transferable lessons might look like for countries carrying a much heavier burden of preventable cervical cancer.</p><p>We also hope to hear directly from researchers and leaders who have helped shape Australia’s elimination effort through forthcoming Conversations Across the Cancer Care Ecosystem.</p><p>Because the most interesting question is no longer whether cervical cancer can be prevented.</p><p>We know that it can.</p><p>The question is whether we can build health systems capable of delivering that promise:</p><p className="insight-pull-statement">for every woman, everywhere.</p></section>
    </InsightArticle>
  </>;
}
